Use integer indices for Python 3
With Python 3 we get the error

    TypeError: slice indices must be integers or None or have an __index__ method

This is because in Python 3, an integer divided by an integer gives a
float with a possible fractional part. In Python 2 the result is truncatd
to integer.

Fix split points to integer.